//! Per-symbol source-fidelity expectations for decompiler fixtures.
//!
//! Add an entry whenever a new exported function is added under
//! `testdata/decompiler_fixtures/src/`.
//!
//! Tiers track arm_decompiler quality vs Ghidra-shaped output (clang -O0 arm64).
//! Promote Smoke → Structural → SourceLike as milestones land — see
//! `docs/DECOMPILER_TEST_PLAN.md`.

use super::fixture_harness::{CompareTier, FixtureSpec};

const NONE: &[&str] = &[];

pub fn fixture_manifest() -> &'static [FixtureSpec] {
    use CompareTier::{Smoke, SourceLike, Structural};
    &[
        // ── arithmetic (M2: locals + prototypes) ─────────────────────────────
        FixtureSpec {
            group: "arithmetic",
            symbol: "_add1",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["int param_1", "int local_", "return (local_"],
            must_not_contain: &["*((sp", "sp = ("],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "arithmetic",
            symbol: "_absdiff",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["if (", "param_1", "param_2", "local_"],
            must_not_contain: &["flags.", "goto"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "arithmetic",
            symbol: "_mul_add",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["param_1", "param_2", "param_3", "local_", "return"],
            must_not_contain: &["*((sp"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "arithmetic",
            symbol: "_main",
            tier: Structural,
            source_ids: false,
            must_contain: &["local_1c", "local_18", "_absdiff", "_add1"],
            must_not_contain: &["x0_", "local_1c = local_28"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        // ── control_flow ─────────────────────────────────────────────────────
        FixtureSpec {
            group: "control_flow",
            symbol: "_if_else",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["if (", "param_1", "local_"],
            must_not_contain: &["flags.", "goto"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "control_flow",
            symbol: "_if_else_chain",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["if (", "param_1", "local_"],
            must_not_contain: &["goto"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "control_flow",
            symbol: "_nested_if",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["if (", "param_1", "local_"],
            must_not_contain: &["goto"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "control_flow",
            symbol: "_while_sum",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["while (", "param_1", "local_"],
            must_not_contain: &["*((sp", "goto"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "control_flow",
            symbol: "_do_while_count",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["do {", "while (", "param_1"],
            must_not_contain: &["*((sp", "goto"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "control_flow",
            symbol: "_for_sum",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["for (", "local_"],
            must_not_contain: &["goto"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "control_flow",
            symbol: "_break_in_loop",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["while (", "break;", "local_"],
            must_not_contain: &["goto"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "control_flow",
            symbol: "_continue_in_loop",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["for (", "if (", "local_"],
            must_not_contain: &["goto", "} else {"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        // ── calls ────────────────────────────────────────────────────────────
        FixtureSpec {
            group: "calls",
            symbol: "_call_add1",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["_add1(", "param_1", "local_"],
            must_not_contain: &["stp ", "ldp ", "*((sp"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "calls",
            symbol: "_call_absdiff",
            tier: Structural,
            source_ids: false,
            must_contain: &["_absdiff(", "local_"],
            must_not_contain: &["stp "],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        // ── switch (M3) ──────────────────────────────────────────────────────
        FixtureSpec {
            group: "switch",
            symbol: "_switch_small",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["switch (", "case ", "local_", "0xa"],
            must_not_contain: &["goto"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "switch",
            symbol: "_switch_sparse",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["switch (", "case ", "local_"],
            must_not_contain: &["goto"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "switch_dense",
            symbol: "_switch_dense",
            tier: Structural,
            source_ids: false,
            must_contain: &["jump table", "switch (", "case 0:", "case 31:"],
            must_not_contain: &["_objc_msgSend("],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "objc",
            symbol: "_cd_smoke_call",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["[self hello:", "local_"],
            must_not_contain: &["goto", "_objc_msgSend(", "[local_"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "objc",
            symbol: "_cd_smoke_sum",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["[self sum:", "with:", "local_"],
            must_not_contain: &["goto", "_objc_msgSend(", "[local_"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "objc",
            symbol: "-[CDSmoke hello:]",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["- (int)hello:", "self", "return"],
            must_not_contain: &["goto", "_objc_msgSend("],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "objc",
            symbol: "_cd_run_block",
            tier: Structural,
            source_ids: false,
            must_contain: &["Block invoke", "local_18(", "local_1c"],
            must_not_contain: &["goto"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        FixtureSpec {
            group: "objc",
            symbol: "_cd_make_and_run",
            tier: Smoke,
            source_ids: false,
            must_contain: &["param_1", "return"],
            must_not_contain: &["goto"],
            skip_source_ids: NONE,
            macho_rel: None,
            source_rel: None,
        },
        // ── swift (Phase 6) ──────────────────────────────────────────────────
        FixtureSpec {
            group: "swift",
            symbol: "_$s5smoke5helloSiyF",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["func smoke.hello(", "-> Int", "return 1"],
            must_not_contain: &["undefined8 _$s", "swift_retain"],
            skip_source_ids: NONE,
            macho_rel: Some("swift_fixtures/libsmoke.dylib"),
            source_rel: Some("swift_fixtures/smoke.swift"),
        },
        FixtureSpec {
            group: "swift",
            symbol: "_$s5smoke4add1yS2iF",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["func smoke.add1(", "-> Int", "param_1", "return"],
            must_not_contain: &["undefined8 _$s", "swift_retain", "cset ", "(x0 +"],
            skip_source_ids: NONE,
            macho_rel: Some("swift_fixtures/libsmoke.dylib"),
            source_rel: Some("swift_fixtures/smoke.swift"),
        },
        FixtureSpec {
            group: "swift",
            symbol: "_$s5smoke7absdiffyS2i_SitF",
            tier: Structural,
            source_ids: false,
            must_contain: &["func smoke.absdiff(", "-> Int", "if ("],
            must_not_contain: &["swift_retain"],
            skip_source_ids: NONE,
            macho_rel: Some("swift_fixtures/libsmoke.dylib"),
            source_rel: Some("swift_fixtures/smoke.swift"),
        },
        FixtureSpec {
            group: "swift",
            symbol: "_$s5smoke7CounterV4bumpSiyF",
            tier: SourceLike,
            source_ids: false,
            must_contain: &["func bump(", "-> Int", "self", "self.value"],
            must_not_contain: &["swift_retain", "undefined8 _$s", "cset ", "*(self)"],
            skip_source_ids: NONE,
            macho_rel: Some("swift_fixtures/libsmoke.dylib"),
            source_rel: Some("swift_fixtures/smoke.swift"),
        },
        FixtureSpec {
            group: "swift",
            symbol: "_$s5smoke5greetSSyF",
            tier: Smoke,
            source_ids: false,
            must_contain: &["func smoke.greet(", "-> String"],
            must_not_contain: &["swift_retain"],
            skip_source_ids: NONE,
            macho_rel: Some("swift_fixtures/libsmoke.dylib"),
            source_rel: Some("swift_fixtures/smoke.swift"),
        },

    ]
}
